Repository Navideck/volumedeck_sdk_flutter, pull requests merged in 2024-02, with the labels that each got.

#15 Update README.md
  README.md
Labels: documentation, enhancement, Review effort [1-5]: 1

#17 Bump android native library to 1.6.0
  CHANGELOG.md
  android/build.gradle
  android/src/main/kotlin/com/navideck/volumedeck_flutter/VolumedeckFlutterPlugin.kt
  android/src/main/kotlin/com/navideck/volumedeck_flutter/VolumedeckGenerated.g.kt
  example/android/app/build.gradle
  example/android/build.gradle
  example/ios/Flutter/AppFrameworkInfo.plist
  example/ios/Podfile
  example/ios/Podfile.lock
  example/ios/Runner.xcodeproj/project.pbxproj
  example/lib/main.dart
  example/pubspec.lock
  ios/Classes/VolumedeckGenerated.g.swift
  lib/src/android_config.dart
  lib/src/generated/volumedeck_generated.g.dart
  lib/src/volumedeck.dart
  pigeons/volumedeck.dart
  pubspec.yaml
Labels: enhancement, Review effort [1-5]: 2

#18 Update readme
  README.md
Labels: documentation, Review effort [1-5]: 1
